"""
ai_executive_summary.py
Enterprise Marketing Analytics & Customer 360 Platform

Purpose: Generate executive_summary.md from KPI data using a structured template.
         Optional LLM enhancement when OPENAI_API_KEY is set in .env
Status:  PLACEHOLDER — run after generate_kpi_report.py

Usage:
    python src/ai_executive_summary.py
    python src/ai_executive_summary.py --use-llm   # optional, requires API key
"""

from datetime import datetime
from pathlib import Path

import duckdb

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = PROJECT_ROOT / "data" / "processed" / "olist_analytics.duckdb"
OUTPUT_PATH = PROJECT_ROOT / "reports" / "executive_summary.md"


def load_kpi_snapshot() -> dict:
    """
    Pull executive KPI snapshot from database.
    Returns empty dict if view is not available — no fake numbers injected.
    """
    if not DB_PATH.exists():
        print(f"Database not found: {DB_PATH}")
        return {}

    conn = duckdb.connect(str(DB_PATH), read_only=True)
    try:
        df = conn.execute("SELECT * FROM kpi_executive_snapshot").fetchdf()
        if df.empty:
            return {}
        return df.iloc[0].to_dict()
    except Exception as exc:
        print(f"KPI snapshot unavailable: {exc}")
        return {}
    finally:
        conn.close()


def build_template_summary(kpis: dict) -> str:
    """
    Build markdown executive summary from real KPI values.
    Uses placeholders when KPIs are not yet available.
    """
    report_date = datetime.now().strftime("%Y-%m-%d")

    if not kpis:
        return f"""# Executive Summary

**Report date:** {report_date}  
**Status:** PLACEHOLDER — awaiting KPI data from analytics pipeline

## Overview

This report will be auto-generated once the Olist dataset is loaded and KPI SQL views are active.

## Key Metrics

| KPI | Value |
|-----|-------|
| Total Revenue | _pending_ |
| Total Orders | _pending_ |
| Total Customers | _pending_ |
| Average Order Value | _pending_ |
| Repeat Purchase Rate | _pending_ |
| Avg Review Score | _pending_ |
| Delivery Delay Rate | _pending_ |

## Next Steps

1. Download Olist CSVs to `data/raw/`
2. Run `python src/data_cleaning.py`
3. Run `python src/load_to_database.py --init-schema`
4. Re-run this script to populate with real metrics

---
_Auto-generated by ai_executive_summary.py_
"""

    # Build summary from real KPI dict (keys match kpi_executive_snapshot view)
    lines = [
        "# Executive Summary",
        "",
        f"**Report date:** {report_date}",
        f"**Data source:** Olist Brazilian E-Commerce",
        "",
        "## Key Metrics",
        "",
        "| KPI | Value |",
        "|-----|-------|",
    ]
    label_map = {
        "total_revenue": "Total Revenue (BRL)",
        "total_orders": "Total Orders",
        "total_customers": "Total Customers",
        "average_order_value": "Average Order Value (BRL)",
        "repeat_purchase_rate_pct": "Repeat Purchase Rate (%)",
        "avg_review_score": "Avg Review Score",
        "delivery_delay_rate_pct": "Delivery Delay Rate (%)",
    }
    for key, label in label_map.items():
        value = kpis.get(key, "N/A")
        lines.append(f"| {label} | {value} |")

    lines.extend(
        [
            "",
            "## Insights",
            "",
            "_PLACEHOLDER: Add narrative insights after Phase 3 analysis, "
            "or enable --use-llm for AI-assisted narrative._",
            "",
            "---",
            "_Auto-generated by ai_executive_summary.py_",
        ]
    )
    return "\n".join(lines)


def enhance_with_llm(summary: str, kpis: dict) -> str:
    """
    Optional: send KPI JSON + template to an LLM for narrative enhancement.
    Requires openai package and OPENAI_API_KEY in .env
    """
    # PLACEHOLDER: implement in Phase 3 when user opts in
    # from dotenv import load_dotenv
    # load_dotenv()
    # import openai
    print("LLM enhancement not yet configured. Using template summary.")
    return summary


def main(use_llm: bool = False) -> None:
    """Generate executive summary markdown file."""
    print("Generating executive summary...")
    kpis = load_kpi_snapshot()
    summary = build_template_summary(kpis)

    if use_llm and kpis:
        summary = enhance_with_llm(summary, kpis)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(summary, encoding="utf-8")
    print(f"Summary saved: {OUTPUT_PATH}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate executive summary")
    parser.add_argument(
        "--use-llm",
        action="store_true",
        help="Enhance narrative with LLM (requires OPENAI_API_KEY)",
    )
    args = parser.parse_args()
    main(use_llm=args.use_llm)
